sudo: required
services:
  - docker

before_install:
  - docker build -t cesqueda/docker-react -f Dockerfiles.dev . 

script:
  - docker run -e CI=true cesqueda/docker-react npm run test -- --coverage